### PR TITLE
chore: make type and setversion configurable

### PR DESCRIPTION
**Pull request by LeoColomb**
> https://github.com/vojtajina/grunt-bump/pull/83#issuecomment-71940945
   sorry this got left but can you squash the commits down to 1 commit please

It's the third time I'm doing it.
You may consider changing your CONTRIBUTING with "No contribution allowed", it will be the same.
Or read this, may be: http://keepachangelog.com/#why-can-t-people-just-use-a-code-git-log-code-diff-

### CODE REVIEW

**Comment by eddiemonge** [comment]
No need to be snarky. Contributions are allowed and merged in and very much appreciated. It means people are using the plugin and like it enough to want to help. However, those contributions should maintain a high standard and seem like they were written by the same person who wrote the rest of the code to make it easier to maintain. Thats why I'm so picky on things like that. The commit message makes it easier to manage a changelog and let people parse the commit log easier.

2 things on this:
 * Missing a readme section to explain the option. Undocumented options means they can be removed since users shouldn't be using them.
 * This isn't a `chore` commit. Its a `feat`: https://github.com/vojtajina/grunt-bump/blob/master/CONTRIBUTING.md#type

**Comment by LeoColomb** [comment]
> However, those contributions should maintain a high standard and seem like they were written by the same person who wrote the rest of the code to make it easier to maintain.

I understand, of course.
But my PR is open for 6 months, now. Every time I'm doing what you want to please your commit restrictions, you reply 2 months later "Hey! Your commit is wrong: please do this. Happy next 2 months!". ([May be?](https://github.com/blog/1943-how-to-write-the-perfect-pull-request))

Also it's quite interesting to see that almost all current PR are blocked by your so hard guidelines. Remember that contributor are mainly [human](http://keepachangelog.com/#why-can-t-people-just-use-a-code-git-log-code-diff-), who apply human behavior in their creation including commits. They're not machine, and asking _fourth times_ to change a not so required thing is pretty discouraging.

So I'm not "snarky", I'm a little bit upset to hear that you love contributions whereas you reject any contribution on hard rules without be interested in the human work just _a second_.

So merge it or not, as you want, but don't expect me to do some more effort.

**Comment by eddiemonge** [comment]
Added in https://github.com/vojtajina/grunt-bump/commit/19532ad40176c1d19d3ed0fe5ec81a67c0294f2f but using different cli/config params. let me know if this works for you.

**Comment by max-mykhailenko** [comment]
How can I use setVersion from without command line?
ex. `bump:setVersion:1.2.25`

**Comment by eddiemonge** [comment]
`bump --setversion=1.2.25`

**Pull request closed without merging**
