### PR TITLE
<feat>(app): Add ability to create a branch before committing

### PR DESCRIPTION
**Pull request by jdforsythe**
Add options to create a release branch before committing and pushing

### CODE REVIEW

**Comment by jdforsythe** [comment]
This change allows you to use the newBranch and newBranchName options to checkout a new release-x.x.x branch before committing and pushing to origin. This allows you to more quickly create a release by using the one command instead of creating the release branch, then running grunt bump. There's also a command-line option to override the config. For instance, we'd use this to create release candidates, but infrequently we want to bump the version inside the release branch. So in our Gruntfile.js we'd set newBranch to true, but we can pass the --newbranch=false command line option to not create a new branch when we're bumping inside the release branch.

**Comment by eddiemonge** [comment]
That process sounds like a lot of work. You could automate this in other ways with other plugins combined with this one

**Comment by jdforsythe** [comment]
It's really simple actually with these changes. Mostly a version bump comes with a release branch, so we just run grunt bump. For the rare occasions we don't want a release branch, we just override it on the command line. This plugin with the newBranch options have saved a good bit of time.

**Comment by eddiemonge** [comment]
Isn't the tag enough for this?

**Comment by jdforsythe** [comment]
As in my comment on #133 this functionality can't be emulated using tags as it's for the Gitflow workflow (some others, as well) which require separate branches that aren't actual releases, which is what tags are for.

**Comment by mojoaxel** [comment]
I'm closing this because of inactivity. If anybody still things we need something like this please feel free to open a new issue/pull request.

**Pull request closed without merging**
