### PR TITLE
Adding option to add untracked files before a commit is performed.

### PR DESCRIPTION
**Pull request by meenie**
As the title says :).  It's something we need for our internal projects.  If you don't want to merge, we'll just use our forked version.

### CODE REVIEW

**Comment by eddiemonge** [comment]
@rpocklin you have a separate changelog for every version?

I still don't know about this. I try to close it and type up the reasons why and then immediately counter them but am still afraid of the implications of this. There has to be a better way. I think if the added files were part of a grunt/glob match then I would feel far more comfortable. Then you can specify which files would be generated that are to be added instead of adding everything blindly. Yeah, I am going with that. If you want to change this so it uses a pattern matcher then I'll accept it. Until then, I am closing this one.

**Comment by meenie** [comment]
@eddiemonge Fair enough :).  That sounds like a great addition to this PR.

**Comment by eddiemonge** [comment]
If you have time and the motivation to do it, I encourage you to update the pr with that functionality. If not, want to make an issue for someone else to tackle it?

**Comment by meenie** [comment]
I can't 100% commit to it, so might as well create the issue to track it.  If/when I update this PR I will link to it.

**Comment by joshuahiggins** [comment]
Ah, I didn't notice this thread before submitting my own pull request, #120, which seems to mimic @meenie's nearly identically. 

On that note, I agree with @meenie's statements in this thread. This repo has already made the assumptions that it can add, commit, and push your git process, so it needs to offer the ability to control the finer aspects of adding, committing, and pushing. If someone's using an untracked option without understanding what it's doing, you can't feel responsible for that. I personally think `push` and `pushTo` are far scarier options then just committing untracked files.

**Comment by mischah** [comment]
Hi,

I would love to see this merged. But agree that it could be safer to make use of glob match to gain a little bit of control what is added.

Background:
I have the same usecase as @meenie.
My release tasks are generating files in my `dist` directory which is in version control.
When there are new files (which are already added and commited in my `src` directory) they are untracked in `dist` after running one of my release tasks.

**Pull request closed without merging**
