### PR TITLE
feat: support custom regexp

### PR DESCRIPTION
**Pull request by Anonym-tsk**
Support custom regexp parsing using options: { regexp: /regexString/ }

### CODE REVIEW

**Comment by eddiemonge** [comment]
thought I already merged this for some reason. Need to do some testing to make sure it works before though.

**Comment by eddiemonge** [comment]
Needs a rebase on top of the semver update.

**Comment by Anonym-tsk** [comment]
Done

**Comment by eddiemonge** [comment]
gut feeling says the option should be `options.regExp`.

@schechter can you confirm the escaping on the regex is good?

**Comment by schechter** [comment]
Yes, I've tested the new RegExp with all bumping options and it is working as expected.

Additionally, the `[\\d||A-a|.|-]*` portion can also be removed and all bumping options still work (with and without a prereleaseName) if you want to take this opportunity to shorten the RegExp.
i.e.:`var VERSION_REGEXP = opts.regexp || new RegExp('([\'|\"]?version[\'|\"]?[ ]*:[ ]*[\'|\"]?)(\\d+\\.\\d+\\.\\d+(-' + opts.prereleaseName + '\\.\\d+)?(-\\d+)?)([\'|\"]?)', 'i');`

**Comment by eddiemonge** [comment]
that would make a nice pr

**Comment by schechter** [comment]
Will look into that one more 1st  (actually I'd like to add some tests around that before make more changes to the RegExp. (I think it would need to take into account the possible differences if the option for git describe are changed.)

**Pull request closed without merging**
